name: Release

on:
  push:
    branches: [main, next]

env:
  SEMANTIC_RELEASE_VERSION: 22.0.12

jobs:
  release:
    name: Semantic release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: Gandalf
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.GANDALF_APP_ID }}
          private-key: ${{ secrets.GANDALF_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Needs to fetch historical commits in order to compare with origin/main
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable --check-cache
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Semantic release
        env:
          GIT_AUTHOR_NAME: ${{ vars.GANDALF_NAME }}
          GIT_AUTHOR_EMAIL: ${{ vars.GANDALF_EMAIL }}
          GIT_COMMITTER_NAME: ${{ vars.GANDALF_NAME }}
          GIT_COMMITTER_EMAIL: ${{ vars.GANDALF_EMAIL }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
        run: |
          yarn dlx --package @semantic-release/commit-analyzer --package @semantic-release/release-notes-generator --package @semantic-release/npm --package @semantic-release/github --package @semantic-release/git --package @semantic-release/changelog --package semantic-release@${{ env.SEMANTIC_RELEASE_VERSION }} semantic-release
